config/routes.rb
Rails.application.routes.draw do

  root 'home#inicio'
  devise_for :usuarios, controllers: { registrations: "registrations", omniauth_callbacks: 'usuarios/omniauth_callbacks'}
  post "/custom_sign_up", to: "usuarios/omniauth_callbacks#custom_sign_up"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :imagen, ImagenUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |usuario|
      if auth[:info]
        usuario.email = auth.info.email
        usuario.nombre = auth[:info][:name]
        usuario.imagen = auth.info.image
      end
      usuario.password = Devise.friendly_token[0,20]
    end
  end

  def self.from_omniauth_goo(access_token)
    data = access_token.info
    usuario = Usuario.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless usuario
        usuario = Usuario.create(nnombre: data['name'],
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    usuario
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :store_current_location, :unless => :devise_controller?

  private
    def store_current_location
      store_location_for(:usuario, request.url)
    end

    def after_sign_out_path_for(resource)
      request.referrer || root_path
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def inicio
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # Para regresar a la anterior página después de 'sign up'
  protected
    def after_sign_up_path_for(resource)
      request.referrer || root_path
    end

    def after_inactive_sign_up_path_for(resource)
      request.referrer || root_path
    end

    def after_update_path_for(resource)
      request.referrer || root_path
    end

  # Para agregar el campo nombre
  private
    def sign_up_params
      params.require(:usuario).permit(:imagen, :imagen_cache, :nombre, :email, :password, :password_confirmation)
    end
    def account_update_params
      params.require(:usuario).permit(:imagen, :imagen_cache, :nombre, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/usuarios/omniauth_callbacks_controller.rb
class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # auth = request.env["omniauth.auth"]
    # raise auth.to_yaml
    @usuario = Usuario.from_omniauth(request.env["omniauth.auth"])
    if @usuario.persisted?
      @usuario.remember_me = true
      sign_in_and_redirect @usuario, event: :authentication # this will throw if @usuario is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      return
    end
    session["devise.auth"] = request.env["omniauth.auth"]
    render :edit
  end
  def custom_sign_up
    @usuario = Usuario.from_omniauth(session["devise.auth"])
    if @usuario.update(usuario_params)
      sign_in_and_redirect @usuario, event: :authentication
    else
      render :edit
    end
  end

  def google_oauth2
    # auth = request.env["omniauth.auth"]
    # raise auth.to_yaml
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @usuario = Usuario.from_omniauth_goo(request.env['omniauth.auth'])

    if @usuario.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @usuario, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_usuario_registration_url, alert: @usuario.errors.full_messages.join("\n")
    end
  end

  def failure
    #redirect_to root_path
    redirect_to new_usuario_session_path, notice: "No pudimos loguearte,
    Error: #{params[:error_description]}, Motivo: #{params[:error_reason]}"
  end

  private
    def usuario_params
      params.require(:usuario).permit(:nombre, :email, :imagen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/inicio.haml
%h1 Bienvenido a la página
-if usuario_signed_in?
  =link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete
c
c
c
c
%hr
c
c

c
%hr
c
c
%hr
c
%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
}%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
}%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr
%hr
c
c

c
%hr
c
c
%hr

cc
c
c
c
c


c






















ccc
c
c
c
c
cc

c

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10">
    <% if flash[:notice] %>
      <% flash.each do |name, msg| %>
        <div class='alert alert-success alert-dismissible'>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </div>
      <% end %>
    <% else %>
      <% flash.each do |name, msg| %>
        <div class='alert alert-info alert-dismissible'>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-custom py-md-4">
  <%= link_to 'INICIO', root_path, class:"navbar-brand btn btn-primary btn-lg" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <i class="fas fa-bars"></i>
  </button>
  <div class="collapse navbar-collapse justify-content-stretch" id="collapsibleNavbar">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link btn btn-outline-secondary btn-lg" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-outline-secondary btn-lg" href="#">Link</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if usuario_signed_in? %>
      <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle btn btn-outline-secondary btn-lg" href="#" id="navbardrop" data-toggle="dropdown"> <%= current_usuario.nombre %></a>
          <div class="dropdown-menu">
            <%= link_to 'Cerrar Sesión', destroy_usuario_session_path, method: :delete, class:"dropdown-item" %>
            <%= link_to "Editar usuario", edit_usuario_registration_path, class:"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_usuario_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_usuario_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_navigation2.html.erb
<nav id="nav2">
  <ul id=ul2>
    <li class="litems lipadgra">Segunda navegación</li>
    <li class="litems lipadgra">Item 1</li>
    <li class="litems lipadgra">Item 2</li>
  </ul>
</nav>
<script>
$(document).ready(function(){
  $(window).scroll(function() {
    if ($(document).scrollTop() > 1) {
      $("#nav2").css("height", "100px");
      $(".litems").removeClass("lipadgra");
      $(".litems").addClass("lipadpeq");
    } else {
      $("#nav2").css("height", "200px");
      $(".litems").removeClass("lipadpeq");
      $(".litems").addClass("lipadgra");
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testoco</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1788454621246562',
          cookie     : true,
          xfbml      : true,
          version    : 'v3.1'
        });

        FB.AppEvents.logPageView();

      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="container" style="background-color:white;">
      <h1>HOLA</h1>
      <%= render 'layouts/navigation2' %>
      <div style="height:55px;"></div>
      <%= render 'layouts/messages' %>

      <%= yield %>

    </div>

  </body>
</html>